services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: caradmin
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: carmod
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: caradmin
      DB_PASSWORD: secretpass
      DB_NAME: carmod
    working_dir: /app
    # ❌ Removed the volume so it doesn't overwrite what was built into the container
    # volumes:
    #   - ./car-customizer/server:/app
    command: node index.js

volumes:
  pgdata:
